// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: task.proto

package server

import (
	"context"

	"github.com/WeiXinao/msProject/task/internal/logic"
	"github.com/WeiXinao/msProject/task/internal/svc"
	"github.com/WeiXinao/msProject/api/proto/gen/task/v1"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServiceServer) TaskStages(ctx context.Context, in *v1.TaskStagesRequest) (*v1.TaskStagesResponse, error) {
	l := logic.NewTaskStagesLogic(ctx, s.svcCtx)
	return l.TaskStages(in)
}

func (s *TaskServiceServer) SaveTaskStages(ctx context.Context, in *v1.SaveTaskStagesRequest) (*v1.SaveTaskStagesResponse, error) {
	l := logic.NewSaveTaskStagesLogic(ctx, s.svcCtx)
	return l.SaveTaskStages(in)
}
