// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: task.proto

package server

import (
	"context"

	"github.com/WeiXinao/msProject/task/internal/logic"
	"github.com/WeiXinao/msProject/task/internal/svc"
	"github.com/WeiXinao/msProject/api/proto/gen/task/v1"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServiceServer) MyTaskList(ctx context.Context, in *v1.MyTaskListRequest) (*v1.MyTaskListResponse, error) {
	l := logic.NewMyTaskListLogic(ctx, s.svcCtx)
	return l.MyTaskList(in)
}

func (s *TaskServiceServer) TaskSort(ctx context.Context, in *v1.TaskSortRequest) (*v1.TaskSortResponse, error) {
	l := logic.NewTaskSortLogic(ctx, s.svcCtx)
	return l.TaskSort(in)
}

func (s *TaskServiceServer) TaskStages(ctx context.Context, in *v1.TaskStagesRequest) (*v1.TaskStagesResponse, error) {
	l := logic.NewTaskStagesLogic(ctx, s.svcCtx)
	return l.TaskStages(in)
}

func (s *TaskServiceServer) SaveTaskStages(ctx context.Context, in *v1.SaveTaskStagesRequest) (*v1.SaveTaskStagesResponse, error) {
	l := logic.NewSaveTaskStagesLogic(ctx, s.svcCtx)
	return l.SaveTaskStages(in)
}

func (s *TaskServiceServer) TaskList(ctx context.Context, in *v1.TaskListRequest) (*v1.TaskListResponse, error) {
	l := logic.NewTaskListLogic(ctx, s.svcCtx)
	return l.TaskList(in)
}

func (s *TaskServiceServer) SaveTask(ctx context.Context, in *v1.SaveTaskRequest) (*v1.TaskMessage, error) {
	l := logic.NewSaveTaskLogic(ctx, s.svcCtx)
	return l.SaveTask(in)
}
