// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: task.proto

package server

import (
	"context"

	"github.com/WeiXinao/msProject/task/internal/logic"
	"github.com/WeiXinao/msProject/task/internal/svc"
	"github.com/WeiXinao/msProject/api/proto/gen/task/v1"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServiceServer) GetLogBySelfProject(ctx context.Context, in *v1.GetLogBySelfProjectRequest) (*v1.GetLogBySelfProjectResponse, error) {
	l := logic.NewGetLogBySelfProjectLogic(ctx, s.svcCtx)
	return l.GetLogBySelfProject(in)
}

func (s *TaskServiceServer) CreateComment(ctx context.Context, in *v1.CreateCommentRequest) (*v1.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *TaskServiceServer) TaskLog(ctx context.Context, in *v1.TaskLogRequest) (*v1.TaskLogResponse, error) {
	l := logic.NewTaskLogLogic(ctx, s.svcCtx)
	return l.TaskLog(in)
}

func (s *TaskServiceServer) CreateProjectLog(ctx context.Context, in *v1.CreateProjectLogRequest) (*v1.CreateProjectLogResponse, error) {
	l := logic.NewCreateProjectLogLogic(ctx, s.svcCtx)
	return l.CreateProjectLog(in)
}

func (s *TaskServiceServer) SaveTaskWorkTime(ctx context.Context, in *v1.SaveTaskWorkTimeRequest) (*v1.SaveTaskWorkTimeResponse, error) {
	l := logic.NewSaveTaskWorkTimeLogic(ctx, s.svcCtx)
	return l.SaveTaskWorkTime(in)
}

func (s *TaskServiceServer) TaskWorkTimeList(ctx context.Context, in *v1.TaskWorkTimeRequest) (*v1.TaskWorkTimeResponse, error) {
	l := logic.NewTaskWorkTimeListLogic(ctx, s.svcCtx)
	return l.TaskWorkTimeList(in)
}

func (s *TaskServiceServer) ListTaskMember(ctx context.Context, in *v1.ListTaskMemberRequest) (*v1.ListTaskMemberResponse, error) {
	l := logic.NewListTaskMemberLogic(ctx, s.svcCtx)
	return l.ListTaskMember(in)
}

func (s *TaskServiceServer) ReadTask(ctx context.Context, in *v1.ReadTaskRequest) (*v1.TaskMessage, error) {
	l := logic.NewReadTaskLogic(ctx, s.svcCtx)
	return l.ReadTask(in)
}

func (s *TaskServiceServer) MyTaskList(ctx context.Context, in *v1.MyTaskListRequest) (*v1.MyTaskListResponse, error) {
	l := logic.NewMyTaskListLogic(ctx, s.svcCtx)
	return l.MyTaskList(in)
}

func (s *TaskServiceServer) TaskSort(ctx context.Context, in *v1.TaskSortRequest) (*v1.TaskSortResponse, error) {
	l := logic.NewTaskSortLogic(ctx, s.svcCtx)
	return l.TaskSort(in)
}

func (s *TaskServiceServer) TaskStages(ctx context.Context, in *v1.TaskStagesRequest) (*v1.TaskStagesResponse, error) {
	l := logic.NewTaskStagesLogic(ctx, s.svcCtx)
	return l.TaskStages(in)
}

func (s *TaskServiceServer) SaveTaskStages(ctx context.Context, in *v1.SaveTaskStagesRequest) (*v1.SaveTaskStagesResponse, error) {
	l := logic.NewSaveTaskStagesLogic(ctx, s.svcCtx)
	return l.SaveTaskStages(in)
}

func (s *TaskServiceServer) TaskList(ctx context.Context, in *v1.TaskListRequest) (*v1.TaskListResponse, error) {
	l := logic.NewTaskListLogic(ctx, s.svcCtx)
	return l.TaskList(in)
}

func (s *TaskServiceServer) SaveTask(ctx context.Context, in *v1.SaveTaskRequest) (*v1.TaskMessage, error) {
	l := logic.NewSaveTaskLogic(ctx, s.svcCtx)
	return l.SaveTask(in)
}
