// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetCaptchaReq struct {
	Mobile string `form:"mobile"`
}

type GetCaptchaResp struct {
	Captcha string `json:"captcha"`
}

type IndexReq struct {
	Token string `header:"Authorization,optional"`
}

type IndexRsp struct {
	Menus []*MenuMessage `json:"menus"`
}

type LoginReq struct {
	Account  string `form:"account"`
	Password string `form:"password"`
}

type LoginRsp struct {
	Member           Member             `json:"member"`
	TokenList        TokenList          `json:"tokenList"`
	OrganizationList []OrganizationList `json:"organizationList"`
}

type Member struct {
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
	Status int    `json:"status"`
	Code   string `json:"code"`
}

type MenuMessage struct {
	Id         int64          `json:"id"`
	Pid        int64          `json:"pid"`
	Title      string         `json:"title"`
	Icon       string         `json:"icon"`
	Url        string         `json:"url"`
	FilePath   string         `json:"filePath"`
	Params     string         `json:"params"`
	Node       string         `json:"node"`
	Sort       int32          `json:"sort"`
	Status     int32          `json:"status"`
	CreateBy   int64          `json:"createBy"`
	IsInner    int32          `json:"isInner"`
	Values     string         `json:"values"`
	ShowSlider int32          `json:"showSlider"`
	Children   []*MenuMessage `json:"children"`
}

type OrganizationList struct {
	Name        string `json:"name"`
	Avatar      string `json:"avatar"`
	Description string `json:"description"`
	MemberId    int64  `json:"memberId"`
	CreateTime  int64  `json:"createTime"`
	Personal    int32  `json:"personal"`
	Address     string `json:"address"`
	Province    int32  `json:"province"`
	City        int32  `json:"city"`
	Area        int32  `json:"area"`
	Code        string `json:"code"`
}

type RegisterReq struct {
	Email     string `form:"email"`
	Name      string `form:"name"`
	Password  string `form:"password"`
	Password2 string `form:"password2"`
	Mobile    string `form:"mobile"`
	Captcha   string `form:"captcha"`
}

type RegisterResp struct {
}

type TokenList struct {
	AccessToken    string `json:"accessToken"`
	RefreshToken   string `json:"refreshToken"`
	TokenType      string `json:"tokenType"`
	AccessTokenExp int64  `json:"accessTokenExp"`
}
