// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetCaptchaReq struct {
	Mobile string `form:"mobile"`
}

type GetCaptchaResp struct {
	Captcha string `json:"captcha"`
}

type IndexReq struct {
	Token string `header:"Authorization,optional"`
}

type IndexRsp struct {
	Menus []*MenuMessage `json:"menus"`
}

type LoginReq struct {
	Account  string `form:"account"`
	Password string `form:"password"`
}

type LoginRsp struct {
	Member           Member             `json:"member"`
	TokenList        TokenList          `json:"tokenList"`
	OrganizationList []OrganizationList `json:"organizationList"`
}

type Member struct {
	Name   string `json:"name"`
	Mobile string `json:"mobile"`
	Status int    `json:"status"`
	Code   string `json:"code"`
}

type MenuMessage struct {
	Id         int64          `json:"id"`
	Pid        int64          `json:"pid"`
	Title      string         `json:"title"`
	Icon       string         `json:"icon"`
	Url        string         `json:"url"`
	FilePath   string         `json:"filePath"`
	Params     string         `json:"params"`
	Node       string         `json:"node"`
	Sort       int32          `json:"sort"`
	Status     int32          `json:"status"`
	CreateBy   int64          `json:"createBy"`
	IsInner    int32          `json:"isInner"`
	Values     string         `json:"values"`
	ShowSlider int32          `json:"showSlider"`
	Children   []*MenuMessage `json:"children"`
}

type OrganizationList struct {
	Name        string `json:"name"`
	Avatar      string `json:"avatar"`
	Description string `json:"description"`
	MemberId    int64  `json:"memberId"`
	CreateTime  int64  `json:"createTime"`
	Personal    int32  `json:"personal"`
	Address     string `json:"address"`
	Province    int32  `json:"province"`
	City        int32  `json:"city"`
	Area        int32  `json:"area"`
	Code        string `json:"code"`
}

type Project struct {
	Cover              string  `json:"cover"`
	Name               string  `json:"name"`
	Description        string  `json:"description"`
	AccessControlType  int     `json:"accessControlType"`
	WhiteList          string  `json:"whiteList"`
	Order              int     `json:"order"`
	Deleted            int     `json:"deleted"`
	TemplateCode       string  `json:"templateCode"`
	Schedule           float64 `json:"schedule"`
	CreateTime         string  `json:"createTime"`
	OrganizationCode   int64   `json:"organizationCode"`
	DeletedTime        string  `json:"deletedTime"`
	Private            int     `json:"private"`
	Prefix             string  `json:"prefix"`
	OpenPrefix         int     `json:"openPrefix"`
	Archive            int     `json:"archive"`
	ArchiveTime        int64   `json:"archiveTime"`
	OpenBeginTime      int     `json:"openBeginTime"`
	OpenTaskPrivate    int     `json:"openTaskPrivate"`
	TaskBoardTheme     string  `json:"taskBoardTheme"`
	BeginTime          int64   `json:"beginTime"`
	EndTime            int64   `json:"endTime"`
	AutoUpdateSchedule int     `json:"autoUpdateSchedule"`
	Code               string  `json:"code"`
}

type ProjectAndMember struct {
	Project
	ProjectCode int64  `json:"projectCode"`
	MemberCode  int64  `json:"memberCode"`
	JoinTime    int64  `json:"joinTime"`
	IsOwner     int64  `json:"isOwner"`
	Authorize   string `json:"authorize"`
}

type ProjectMember struct {
	Id          int64  `json:"id"`
	ProjectCode int64  `json:"projectCode"`
	MemberCode  int64  `json:"memberCode"`
	JoinTime    int64  `json:"joinTime"`
	IsOwner     int64  `json:"isOwner"`
	Authorize   string `json:"authorize"`
}

type RegisterReq struct {
	Email     string `form:"email"`
	Name      string `form:"name"`
	Password  string `form:"password"`
	Password2 string `form:"password2"`
	Mobile    string `form:"mobile"`
	Captcha   string `form:"captcha"`
}

type RegisterResp struct {
}

type SelfListReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=10"`
}

type SelfListRsp struct {
	List  []*ProjectAndMember `json:"list"`
	Total int64               `json:"total"`
}

type TokenList struct {
	AccessToken    string `json:"accessToken"`
	RefreshToken   string `json:"refreshToken"`
	TokenType      string `json:"tokenType"`
	AccessTokenExp int64  `json:"accessTokenExp"`
}
