services:
  mysql:
    image: mysql:8.0
    container_name: mymysql8
    privileged: true
    ports:
      - "3307:3306"
    volumes:
      - /root/mysql/log:/var/log/mysql
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  redis:
    image: redis:7.4.0
    container_name: myredis7
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /root/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  etcd:
    image: "bitnami/etcd:3.5.9"
    container_name: etcd-1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "/root/etcd/data:/etcd-data"
