services:
  mysql:
    image: mysql:8.0
    container_name: mymysql8
    privileged: true
    ports:
      - "3307:3306"
    volumes:
      - /root/mysql/log:/var/log/mysql
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  redis:
    image: redis:7.4.0
    container_name: myredis7
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /root/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  etcd:
    image: "bitnami/etcd:3.5.9"
    container_name: etcd1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "/root/etcd/data:/etcd-data"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf 
      - /root/nginx/conf/conf.d:/etc/nginx/conf.d 
      - /root/nginx/log:/var/log/nginx 
      - /root/nginx/html:/usr/share/nginx/html 
  kafka:
    image: "bitnami/kafka:3.6.0"
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
#      允许制动创建 topic，线上不要开启
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER   
#  user:
#    container_name: user-1
#    image: user:latest
#    ports:
#      - 8080:8080