services:
  mysql:
    image: mysql:8.0
    container_name: mymysql8
    privileged: true
    ports:
      - "3307:3306"
    volumes:
      - /root/mysql/log:/var/log/mysql
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
  redis:
    image: redis:7.4.0
    container_name: myredis7
    privileged: true
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /root/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  etcd:
    image: "bitnami/etcd:3.5.9"
    container_name: etcd1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - "/root/etcd/data:/etcd-data"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf 
      - /root/nginx/conf/conf.d:/etc/nginx/conf.d 
      - /root/nginx/log:/var/log/nginx 
      - /root/nginx/html:/usr/share/nginx/html 
#  user:
#    container_name: user-1
#    image: user:latest
#    ports:
#      - 8080:8080