// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: project.proto

package server

import (
	"context"

	"github.com/WeiXinao/msProject/api/proto/gen/project/v1"
	"github.com/WeiXinao/msProject/project/internal/logic"
	"github.com/WeiXinao/msProject/project/internal/svc"
)

type ProjectServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedProjectServiceServer
}

func NewProjectServiceServer(svcCtx *svc.ServiceContext) *ProjectServiceServer {
	return &ProjectServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProjectServiceServer) Index(ctx context.Context, in *v1.IndexRequest) (*v1.IndexResponse, error) {
	l := logic.NewIndexLogic(ctx, s.svcCtx)
	return l.Index(in)
}

func (s *ProjectServiceServer) FindProjectByMemId(ctx context.Context, in *v1.ProjectRequest) (*v1.ProjectResponse, error) {
	l := logic.NewFindProjectByMemIdLogic(ctx, s.svcCtx)
	return l.FindProjectByMemId(in)
}

func (s *ProjectServiceServer) FindProjectTemplate(ctx context.Context, in *v1.FindProjectTemplateRequest) (*v1.FindProjectTemplateResponse, error) {
	l := logic.NewFindProjectTemplateLogic(ctx, s.svcCtx)
	return l.FindProjectTemplate(in)
}

func (s *ProjectServiceServer) SaveProject(ctx context.Context, in *v1.SaveProjectReq) (*v1.SaveProjectRsp, error) {
	l := logic.NewSaveProjectLogic(ctx, s.svcCtx)
	return l.SaveProject(in)
}

func (s *ProjectServiceServer) ProjectDetail(ctx context.Context, in *v1.ProjectDetailRequest) (*v1.ProjectDetailResponse, error) {
	l := logic.NewProjectDetailLogic(ctx, s.svcCtx)
	return l.ProjectDetail(in)
}
