// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: project.proto

package projectservice

import (
	"context"

	"github.com/WeiXinao/msProject/api/proto/gen/project/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IndexRequest  = v1.IndexRequest
	IndexResponse = v1.IndexResponse
	MenuMessage   = v1.MenuMessage

	ProjectService interface {
		Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	}

	defaultProjectService struct {
		cli zrpc.Client
	}
)

func NewProjectService(cli zrpc.Client) ProjectService {
	return &defaultProjectService{
		cli: cli,
	}
}

func (m *defaultProjectService) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.Index(ctx, in, opts...)
}
