// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: project.proto

package projectservice

import (
	"context"

	"github.com/WeiXinao/msProject/api/proto/gen/project/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindProjectTemplateRequest   = v1.FindProjectTemplateRequest
	FindProjectTemplateResponse  = v1.FindProjectTemplateResponse
	IndexRequest                 = v1.IndexRequest
	IndexResponse                = v1.IndexResponse
	MenuMessage                  = v1.MenuMessage
	ProjectDetailRequest         = v1.ProjectDetailRequest
	ProjectDetailResponse        = v1.ProjectDetailResponse
	ProjectMessage               = v1.ProjectMessage
	ProjectRequest               = v1.ProjectRequest
	ProjectResponse              = v1.ProjectResponse
	ProjectTemplateMessage       = v1.ProjectTemplateMessage
	RecycleProjectRequest        = v1.RecycleProjectRequest
	RecycleProjectResponse       = v1.RecycleProjectResponse
	SaveProjectReq               = v1.SaveProjectReq
	SaveProjectRsp               = v1.SaveProjectRsp
	TaskStages                   = v1.TaskStages
	UpdateCollectProjectRequest  = v1.UpdateCollectProjectRequest
	UpdateCollectProjectResponse = v1.UpdateCollectProjectResponse

	ProjectService interface {
		Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
		FindProjectByMemId(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
		FindProjectTemplate(ctx context.Context, in *FindProjectTemplateRequest, opts ...grpc.CallOption) (*FindProjectTemplateResponse, error)
		SaveProject(ctx context.Context, in *SaveProjectReq, opts ...grpc.CallOption) (*SaveProjectRsp, error)
		ProjectDetail(ctx context.Context, in *ProjectDetailRequest, opts ...grpc.CallOption) (*ProjectDetailResponse, error)
		RecycleOrRecoverProject(ctx context.Context, in *RecycleProjectRequest, opts ...grpc.CallOption) (*RecycleProjectResponse, error)
		UpdateCollectProject(ctx context.Context, in *UpdateCollectProjectRequest, opts ...grpc.CallOption) (*UpdateCollectProjectResponse, error)
	}

	defaultProjectService struct {
		cli zrpc.Client
	}
)

func NewProjectService(cli zrpc.Client) ProjectService {
	return &defaultProjectService{
		cli: cli,
	}
}

func (m *defaultProjectService) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.Index(ctx, in, opts...)
}

func (m *defaultProjectService) FindProjectByMemId(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.FindProjectByMemId(ctx, in, opts...)
}

func (m *defaultProjectService) FindProjectTemplate(ctx context.Context, in *FindProjectTemplateRequest, opts ...grpc.CallOption) (*FindProjectTemplateResponse, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.FindProjectTemplate(ctx, in, opts...)
}

func (m *defaultProjectService) SaveProject(ctx context.Context, in *SaveProjectReq, opts ...grpc.CallOption) (*SaveProjectRsp, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.SaveProject(ctx, in, opts...)
}

func (m *defaultProjectService) ProjectDetail(ctx context.Context, in *ProjectDetailRequest, opts ...grpc.CallOption) (*ProjectDetailResponse, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.ProjectDetail(ctx, in, opts...)
}

func (m *defaultProjectService) RecycleOrRecoverProject(ctx context.Context, in *RecycleProjectRequest, opts ...grpc.CallOption) (*RecycleProjectResponse, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.RecycleOrRecoverProject(ctx, in, opts...)
}

func (m *defaultProjectService) UpdateCollectProject(ctx context.Context, in *UpdateCollectProjectRequest, opts ...grpc.CallOption) (*UpdateCollectProjectResponse, error) {
	client := v1.NewProjectServiceClient(m.cli.Conn())
	return client.UpdateCollectProject(ctx, in, opts...)
}
