// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: account.proto

package account_client

import (
	"context"

	"account/account"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = account.Request
	Response = account.Response

	Account interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
