// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	project "github.com/WeiXinao/msProject/bff/internal/handler/project"
	user "github.com/WeiXinao/msProject/bff/internal/handler/user"
	"github.com/WeiXinao/msProject/bff/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/index",
					Handler: project.IndexHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/project"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/getCaptcha",
				Handler: user.GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/project"),
	)
}
