// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package loginservice

import (
	"context"

	userv1 "github.com/WeiXinao/msProject/api/proto/gen/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaptchaRequest  = userv1.CaptchaRequest
	CaptchaResponse = userv1.CaptchaResponse

	LoginService interface {
		GetCaptcha(ctx context.Context, in *CaptchaRequest, opts ...grpc.CallOption) (*CaptchaResponse, error)
	}

	defaultLoginService struct {
		cli zrpc.Client
	}
)

func NewLoginService(cli zrpc.Client) LoginService {
	return &defaultLoginService{
		cli: cli,
	}
}

func (m *defaultLoginService) GetCaptcha(ctx context.Context, in *CaptchaRequest, opts ...grpc.CallOption) (*CaptchaResponse, error) {
	client := userv1.NewLoginServiceClient(m.cli.Conn())
	return client.GetCaptcha(ctx, in, opts...)
}
