// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: account.proto

package server

import (
	"context"

	"account/account"
	"account/internal/logic"
	"account/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Ping(ctx context.Context, in *account.Request) (*account.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
