// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: account.proto

package server

import (
	"context"

	"github.com/WeiXinao/msProject/account/internal/logic"
	"github.com/WeiXinao/msProject/account/internal/svc"
	"github.com/WeiXinao/msProject/api/proto/gen/account/v1"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Account(ctx context.Context, in *v1.AccountRequest) (*v1.AccountResponse, error) {
	l := logic.NewAccountLogic(ctx, s.svcCtx)
	return l.Account(in)
}

func (s *AccountServer) ListDepartments(ctx context.Context, in *v1.ListDepartmentsReqeust) (*v1.ListDepartmentsResponse, error) {
	l := logic.NewListDepartmentsLogic(ctx, s.svcCtx)
	return l.ListDepartments(in)
}
