// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"
	"github.com/WeiXinao/msProject/pkg/paramx"
	"github.com/WeiXinao/msProject/pkg/respx"

	userv1 "github.com/WeiXinao/msProject/api/proto/gen/user/v1"
	"github.com/WeiXinao/msProject/user/internal/logic"
	"github.com/WeiXinao/msProject/user/internal/svc"
)

type LoginServiceServer struct {
	svcCtx *svc.ServiceContext
	userv1.UnimplementedLoginServiceServer
}

func NewLoginServiceServer(svcCtx *svc.ServiceContext) *LoginServiceServer {
	return &LoginServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginServiceServer) GetCaptcha(ctx context.Context, in *userv1.CaptchaRequest) (*userv1.CaptchaResponse, error) {
	// 参数校验
	if !paramx.VerifyMobile(in.Mobile) {
		return nil, respx.IllegalMobile.AsStatusErr()
	}
	l := logic.NewGetCaptchaLogic(ctx, s.svcCtx)
	return l.GetCaptcha(in)
}
