// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"

	userv1 "github.com/WeiXinao/msProject/api/proto/gen/user/v1"
	"github.com/WeiXinao/msProject/user/internal/logic"
	"github.com/WeiXinao/msProject/user/internal/svc"
)

type LoginServiceServer struct {
	svcCtx *svc.ServiceContext
	userv1.UnimplementedLoginServiceServer
}

func NewLoginServiceServer(svcCtx *svc.ServiceContext) *LoginServiceServer {
	return &LoginServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginServiceServer) GetCaptcha(ctx context.Context, in *userv1.CaptchaRequest) (*userv1.CaptchaResponse, error) {
	l := logic.NewGetCaptchaLogic(ctx, s.svcCtx)
	return l.GetCaptcha(in)
}

func (s *LoginServiceServer) Register(ctx context.Context, in *userv1.RegisterRequest) (*userv1.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *LoginServiceServer) Login(ctx context.Context, in *userv1.LoginRequest) (*userv1.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *LoginServiceServer) MyOrgList(ctx context.Context, in *userv1.MyOrgListRequest) (*userv1.MyOrgListResponse, error) {
	l := logic.NewMyOrgListLogic(ctx, s.svcCtx)
	return l.MyOrgList(in)
}

func (s *LoginServiceServer) MemberInfo(ctx context.Context, in *userv1.MemberInfoRequest) (*userv1.MemberInfoResponse, error) {
	l := logic.NewMemberInfoLogic(ctx, s.svcCtx)
	return l.MemberInfo(in)
}
