Name: project.rpc
ListenOn: 0.0.0.0:8081
Etcd:
  Hosts:
  - 192.168.5.4:2379
  Key: project.rpc
RedisConfig:
  Host: "192.168.5.4:6379"
  Type: "node"
  Tls: false
  NonBlock: false
  PingTimeout: 1s
MySQLConfig:
  DriverName: mysql
  Dsn: root:123456@tcp(192.168.5.4:3307)/ms_project?charset=utf8
logConfig:
  debugFileName: "..\\logs\\debug\\project-debug.log"
  infoFileName:  "..\\logs\\info\\project-info.log"
  warnFileName:  "..\\logs\\error\\project-error.log"
  maxSize:       500
  maxAge:        28
  maxBackups:    3
Jwt:
  # 7天
  AccessExp:  "168h"
  # 14天
  RefreshExp: "336h"
  AtKey: "95osj3fUD7fo0mlYdDbncXz4VD2igvf0"
  RtKey: "95osj3fUD7fo0mlYdDbncXz4VD2igvfx"
#  AES 加密 24 byte
AESKey: "123jldjalsdjalkajlds1234"
