// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: task.proto

package taskservice

import (
	"context"

	"github.com/WeiXinao/msProject/api/proto/gen/task/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecutorMessage          = v1.ExecutorMessage
	ListTaskMemberRequest    = v1.ListTaskMemberRequest
	ListTaskMemberResponse   = v1.ListTaskMemberResponse
	Member                   = v1.Member
	MyTaskListRequest        = v1.MyTaskListRequest
	MyTaskListResponse       = v1.MyTaskListResponse
	MyTaskMessage            = v1.MyTaskMessage
	ReadTaskRequest          = v1.ReadTaskRequest
	SaveTaskRequest          = v1.SaveTaskRequest
	SaveTaskStagesMessage    = v1.SaveTaskStagesMessage
	SaveTaskStagesRequest    = v1.SaveTaskStagesRequest
	SaveTaskStagesResponse   = v1.SaveTaskStagesResponse
	SaveTaskWorkTimeRequest  = v1.SaveTaskWorkTimeRequest
	SaveTaskWorkTimeResponse = v1.SaveTaskWorkTimeResponse
	TaskListRequest          = v1.TaskListRequest
	TaskListResponse         = v1.TaskListResponse
	TaskMemberMessage        = v1.TaskMemberMessage
	TaskMessage              = v1.TaskMessage
	TaskSortRequest          = v1.TaskSortRequest
	TaskSortResponse         = v1.TaskSortResponse
	TaskStagesMessage        = v1.TaskStagesMessage
	TaskStagesRequest        = v1.TaskStagesRequest
	TaskStagesResponse       = v1.TaskStagesResponse
	TaskWorkTime             = v1.TaskWorkTime
	TaskWorkTimeRequest      = v1.TaskWorkTimeRequest
	TaskWorkTimeResponse     = v1.TaskWorkTimeResponse

	TaskService interface {
		SaveTaskWorkTime(ctx context.Context, in *SaveTaskWorkTimeRequest, opts ...grpc.CallOption) (*SaveTaskWorkTimeResponse, error)
		TaskWorkTimeList(ctx context.Context, in *TaskWorkTimeRequest, opts ...grpc.CallOption) (*TaskWorkTimeResponse, error)
		ListTaskMember(ctx context.Context, in *ListTaskMemberRequest, opts ...grpc.CallOption) (*ListTaskMemberResponse, error)
		ReadTask(ctx context.Context, in *ReadTaskRequest, opts ...grpc.CallOption) (*TaskMessage, error)
		MyTaskList(ctx context.Context, in *MyTaskListRequest, opts ...grpc.CallOption) (*MyTaskListResponse, error)
		TaskSort(ctx context.Context, in *TaskSortRequest, opts ...grpc.CallOption) (*TaskSortResponse, error)
		TaskStages(ctx context.Context, in *TaskStagesRequest, opts ...grpc.CallOption) (*TaskStagesResponse, error)
		SaveTaskStages(ctx context.Context, in *SaveTaskStagesRequest, opts ...grpc.CallOption) (*SaveTaskStagesResponse, error)
		TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error)
		SaveTask(ctx context.Context, in *SaveTaskRequest, opts ...grpc.CallOption) (*TaskMessage, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

func (m *defaultTaskService) SaveTaskWorkTime(ctx context.Context, in *SaveTaskWorkTimeRequest, opts ...grpc.CallOption) (*SaveTaskWorkTimeResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.SaveTaskWorkTime(ctx, in, opts...)
}

func (m *defaultTaskService) TaskWorkTimeList(ctx context.Context, in *TaskWorkTimeRequest, opts ...grpc.CallOption) (*TaskWorkTimeResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.TaskWorkTimeList(ctx, in, opts...)
}

func (m *defaultTaskService) ListTaskMember(ctx context.Context, in *ListTaskMemberRequest, opts ...grpc.CallOption) (*ListTaskMemberResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.ListTaskMember(ctx, in, opts...)
}

func (m *defaultTaskService) ReadTask(ctx context.Context, in *ReadTaskRequest, opts ...grpc.CallOption) (*TaskMessage, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.ReadTask(ctx, in, opts...)
}

func (m *defaultTaskService) MyTaskList(ctx context.Context, in *MyTaskListRequest, opts ...grpc.CallOption) (*MyTaskListResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.MyTaskList(ctx, in, opts...)
}

func (m *defaultTaskService) TaskSort(ctx context.Context, in *TaskSortRequest, opts ...grpc.CallOption) (*TaskSortResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.TaskSort(ctx, in, opts...)
}

func (m *defaultTaskService) TaskStages(ctx context.Context, in *TaskStagesRequest, opts ...grpc.CallOption) (*TaskStagesResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.TaskStages(ctx, in, opts...)
}

func (m *defaultTaskService) SaveTaskStages(ctx context.Context, in *SaveTaskStagesRequest, opts ...grpc.CallOption) (*SaveTaskStagesResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.SaveTaskStages(ctx, in, opts...)
}

func (m *defaultTaskService) TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.TaskList(ctx, in, opts...)
}

func (m *defaultTaskService) SaveTask(ctx context.Context, in *SaveTaskRequest, opts ...grpc.CallOption) (*TaskMessage, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.SaveTask(ctx, in, opts...)
}
