// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: task.proto

package taskservice

import (
	"context"

	"github.com/WeiXinao/msProject/api/proto/gen/task/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SaveTaskStagesMessage  = v1.SaveTaskStagesMessage
	SaveTaskStagesRequest  = v1.SaveTaskStagesRequest
	SaveTaskStagesResponse = v1.SaveTaskStagesResponse
	TaskStagesMessage      = v1.TaskStagesMessage
	TaskStagesRequest      = v1.TaskStagesRequest
	TaskStagesResponse     = v1.TaskStagesResponse

	TaskService interface {
		TaskStages(ctx context.Context, in *TaskStagesRequest, opts ...grpc.CallOption) (*TaskStagesResponse, error)
		SaveTaskStages(ctx context.Context, in *SaveTaskStagesRequest, opts ...grpc.CallOption) (*SaveTaskStagesResponse, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

func (m *defaultTaskService) TaskStages(ctx context.Context, in *TaskStagesRequest, opts ...grpc.CallOption) (*TaskStagesResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.TaskStages(ctx, in, opts...)
}

func (m *defaultTaskService) SaveTaskStages(ctx context.Context, in *SaveTaskStagesRequest, opts ...grpc.CallOption) (*SaveTaskStagesResponse, error) {
	client := v1.NewTaskServiceClient(m.cli.Conn())
	return client.SaveTaskStages(ctx, in, opts...)
}
