// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: department.proto

package server

import (
	"context"

	"department/department"
	"department/internal/logic"
	"department/internal/svc"
)

type DepartmentServer struct {
	svcCtx *svc.ServiceContext
	department.UnimplementedDepartmentServer
}

func NewDepartmentServer(svcCtx *svc.ServiceContext) *DepartmentServer {
	return &DepartmentServer{
		svcCtx: svcCtx,
	}
}

func (s *DepartmentServer) Ping(ctx context.Context, in *department.Request) (*department.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
