// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: account.proto

package account

import (
	"context"

	"github.com/WeiXinao/msProject/api/proto/gen/account/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountRequest          = v1.AccountRequest
	AccountResponse         = v1.AccountResponse
	DepartmentMessage       = v1.DepartmentMessage
	ListDepartmentsReqeust  = v1.ListDepartmentsReqeust
	ListDepartmentsResponse = v1.ListDepartmentsResponse
	MemberAccount           = v1.MemberAccount
	ProjectAuth             = v1.ProjectAuth

	Account interface {
		Account(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
		ListDepartments(ctx context.Context, in *ListDepartmentsReqeust, opts ...grpc.CallOption) (*ListDepartmentsResponse, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) Account(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	client := v1.NewAccountClient(m.cli.Conn())
	return client.Account(ctx, in, opts...)
}

func (m *defaultAccount) ListDepartments(ctx context.Context, in *ListDepartmentsReqeust, opts ...grpc.CallOption) (*ListDepartmentsResponse, error) {
	client := v1.NewAccountClient(m.cli.Conn())
	return client.ListDepartments(ctx, in, opts...)
}
